# Generated by Django 5.2.8 on 2025-11-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreacionUsu', '0002_remove_cliente_id_cliente_id_cliente'),
        ('pedido', '0002_remove_pedido_producto_pedido_total_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPago',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreacionUsu.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pedido.pedido')),
            ],
        ),
    ]
