# Generated by Django 5.2.8 on 2025-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_movimientopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientopago',
            name='tipo',
            field=models.CharField(choices=[('abono', 'Abono'), ('pago_total', 'Pago Total')], max_length=20),
        ),
    ]
